In [1]:
from google.colab import files
g=files.upload()

Saving labels.csv to labels.csv

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('labels.csv')
#df_im=pd.read_csv('with_images.csv')

In [4]:
df.head(10)

   Unnamed: 0  Black  Blue  Bron  ...  skin_exposure  sleevelength  white  yellow
0           0    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
1           1    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
2           2    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
3           3    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
4           4    1.0   1.0   1.0  ...            2.0           1.0    2.0     1.0
5           5    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
6           6    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
7           7    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
8           8    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
9           9    1.0   1.0   1.0  ...            1.0           3.0    2.0     1.0

[10 rows x 27 columns]

In [5]:
df.shape

(1856, 27)

In [6]:
df.drop(['Category','neckline','pattern_solid'],axis=1,inplace=True)
df.head(20)

    Unnamed: 0  Black  Blue  Bron  ...  skin_exposure  sleevelength  white  yellow
0            0    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
1            1    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
2            2    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
3            3    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
4            4    1.0   1.0   1.0  ...            2.0           1.0    2.0     1.0
5            5    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
6            6    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
7            7    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
8            8    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
9            9    1.0   1.0   1.0  ...            1.0           3.0    2.0     1.0
10          10    1.0   1.0   1.0  ...            2.0           1.0    2.0     1.0
11          11    1.0   1.0   1.0  ...            1.0           3.0    2.0     1.0
12          12    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
13          13    NaN   NaN   NaN  ...            1.0           3.0    NaN     NaN
14          14    1.0   1.0   2.0  ...            1.0           3.0    1.0     1.0
15          15    2.0   1.0   1.0  ...            1.0           3.0    2.0     1.0
16          16    2.0   1.0   1.0  ...            1.0           2.0    1.0     1.0
17          17    NaN   NaN   NaN  ...            1.0           3.0    NaN     NaN
18          18    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
19          19    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0

[20 rows x 24 columns]

In [7]:
df.shape
# df['Collar'].isnull().sum()

(1856, 24)

In [8]:
df['Collar'].replace(np.nan,1.0,inplace=True)

In [63]:
df.head(100
        )

    Index  Black  Blue  Brown  Collar  ...  red  scarf  skin_exposure  white  yellow
0       0    2.0   1.0    1.0     2.0  ...  1.0    1.0            1.0    1.0     1.0
1       1    1.0   1.0    1.0     1.0  ...  1.0    1.0            1.0    1.0     1.0
2       2    2.0   1.0    1.0     2.0  ...  1.0    2.0            1.0    1.0     1.0
3       3    2.0   1.0    1.0     2.0  ...  1.0    1.0            1.0    1.0     1.0
4       4    1.0   1.0    1.0     1.0  ...  1.0    1.0            2.0    2.0     1.0
..    ...    ...   ...    ...     ...  ...  ...    ...            ...    ...     ...
95     95    1.0   1.0    2.0     2.0  ...  1.0    1.0            1.0    2.0     1.0
96     96    2.0   1.0    1.0     2.0  ...  1.0    1.0            1.0    1.0     1.0
97     97    1.0   1.0    1.0     2.0  ...  1.0    1.0            1.0    1.0     1.0
98     98    1.0   1.0    1.0     1.0  ...  1.0    1.0            1.0    2.0     1.0
99     99    2.0   1.0    2.0     2.0  ...  1.0    1.0            1.0    1.0     1.0

[100 rows x 19 columns]

In [12]:
df.head()

   Index  Black  Blue  Bron  ...  skin_exposure  sleevelength  white  yellow
0      0    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
1      1    1.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
2      2    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
3      3    2.0   1.0   1.0  ...            1.0           3.0    1.0     1.0
4      4    1.0   1.0   1.0  ...            2.0           1.0    2.0     1.0

[5 rows x 24 columns]

In [13]:
df=df.rename(columns={'Bron':'Brown'})

In [16]:
df.head(30)
df['Black'].replace(np.nan,1.0,inplace=True)

In [27]:
df['Blue'].replace(np.nan,1.0,inplace=True)
df['Brown'].replace(np.nan,1.0,inplace=True)
df['Cyan'].replace(np.nan,1.0,inplace=True)
df['Gray'].replace(np.nan,1.0,inplace=True)
df['many_colour'].replace(np.nan,1.0,inplace=True)

In [28]:
df.drop(columns=['necktie'],axis=1,inplace=True)

In [33]:
df['pattern_floral'].replace(np.nan,1.0,inplace=True)
df['pattern_graphics'].replace(np.nan,1.0,inplace=True)
df.drop(columns=['pattern_plaid'],axis=1,inplace=True)

KeyError: ignored

In [37]:
df['pattern_spot'].replace(np.nan,1.0,inplace=True)
df['pattern_stripe'].replace(np.nan,1.0,inplace=True)

In [39]:
df.drop(columns=['placket'],axis=1,inplace=True)

In [41]:
df.drop(columns=['purple'],axis=0,inplace=True)

In [52]:
df['red'].replace(np.nan,1.0,inplace=True)
df['scarf'].replace(np.nan,1.0,inplace=True)
df['skin_exposure'].replace(np.nan,1.0,inplace=True)

In [54]:
# df.drop(columns=['seevelength'],axis=0,inplace=True)
df['white'].replace(np.nan,1.0,inplace=True)
df['yellow'].replace(np.nan,1.0,inplace=True)

In [57]:
df.head(4)

   Index  Black  Blue  Brown  Collar  ...  red  scarf  skin_exposure  white  yellow
0      0    2.0   1.0    1.0     2.0  ...  1.0    1.0            1.0    1.0     1.0
1      1    1.0   1.0    1.0     1.0  ...  1.0    1.0            1.0    1.0     1.0
2      2    2.0   1.0    1.0     2.0  ...  1.0    2.0            1.0    1.0     1.0
3      3    2.0   1.0    1.0     2.0  ...  1.0    1.0            1.0    1.0     1.0

[4 rows x 19 columns]

In [58]:
df['Green'].replace(np.nan,1.0,inplace=True)

In [59]:
df.isnull().sum()

Index                0
Black                0
Blue                 0
Brown                0
Collar               0
Cyan                 0
Gender              62
Gray                 0
Green                0
many_colour          0
pattern_floral       0
pattern_graphics     0
pattern_spot         0
pattern_stripe       0
red                  0
scarf                0
skin_exposure        0
white                0
yellow               0
dtype: int64

In [61]:
df.to_csv("finalLabel.csv")
# df=df.rename(columns={'Unnamed: 0':'Index'})

In [62]:
from google.colab import files
files.download("finalLabel.csv")

In [19]:
df.isnull().sum()

Index                 0
Black                 0
Blue                112
Brown               112
Collar                0
Cyan                112
Gender               62
Gray                112
Green               112
many_colour         112
necktie             117
pattern_floral      138
pattern_graphics     78
pattern_plaid       116
pattern_spot        136
pattern_stripe      182
placket              73
purple              112
red                 112
scarf               190
skin_exposure       166
sleevelength         75
white               112
yellow              112
dtype: int64

In [ ]:
df

      Index  Black  Blue  Bron  ...  scarf  skin_exposure  white  yellow
0         0    2.0   1.0   1.0  ...    1.0            1.0    1.0     1.0
1         1    1.0   1.0   1.0  ...    1.0            1.0    1.0     1.0
2         2    2.0   1.0   1.0  ...    2.0            1.0    1.0     1.0
3         3    2.0   1.0   1.0  ...    1.0            1.0    1.0     1.0
4         4    1.0   1.0   1.0  ...    1.0            2.0    2.0     1.0
...     ...    ...   ...   ...  ...    ...            ...    ...     ...
1851   1851    1.0   1.0   1.0  ...    1.0            1.0    1.0     1.0
1852   1852    1.0   1.0   1.0  ...    1.0            2.0    1.0     1.0
1853   1853    1.0   1.0   1.0  ...    1.0            1.0    1.0     1.0
1854   1854    1.0   1.0   1.0  ...    1.0            1.0    1.0     1.0
1855   1855    1.0   2.0   1.0  ...    1.0            2.0    1.0     1.0

[1856 rows x 26 columns]

In [ ]:
df.to_csv("cleanattributes.csv")
from google.colab import files
files.download("cleanattributes.csv")

In [ ]:
df.dtypes

Unnamed: 0            int64
Black               float64
Blue                float64
Bron                float64
Category            float64
Collar              float64
Cyan                float64
Gender              float64
Gray                float64
Green               float64
many_colour         float64
neckline            float64
necktie             float64
pattern_floral      float64
pattern_graphics    float64
pattern_plaid       float64
pattern_solid       float64
pattern_spot        float64
pattern_stripe      float64
placket             float64
purple              float64
red                 float64
scarf               float64
skin_exposure       float64
sleevelength        float64
white               float64
yellow              float64
dtype: object

In [ ]:
df.isnull().sum()

Unnamed: 0            0
Black               112
Blue                112
Bron                112
Category            752
Collar              394
Cyan                112
Gender               62
Gray                112
Green               112
many_colour         112
neckline            542
necktie             117
pattern_floral      138
pattern_graphics     78
pattern_plaid       116
pattern_solid       363
pattern_spot        136
pattern_stripe      182
placket              73
purple              112
red                 112
scarf               190
skin_exposure       166
sleevelength         75
white               112
yellow              112
dtype: int64

In [ ]:
del df['Category']